{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "veritas-sdr.serviceAccountName" . }}
  labels:
    {{- include "veritas-sdr.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
